name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test build
      run: docker-compose up --build
      timeout-minutes: 1
      continue-on-error: true

    - name: Shut down
      run: docker-compose down
